version: "3"
services:
    nodebasic:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ".:/usr/src/app"
            - "/usr/src/app/node_modules"
        ports:
            - '9999:9999'
networks:
  default:
    external:
      name: kafkanettet

