version: "3"
services:
    node:
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ".:/usr/src/app"
            - "/usr/src/app/node_modules"
        ports:
            - '80:3000'
networks:
  default:
    external:
      name: kafkanettet
